### ISSUE TITLE
Performance issues: unleash.x-team.com

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#144]
Avatar grid takes ages to load, the green circle loader is not being displayed. Please take a look under the hood. :)

**Comment by theanxy** [comment]
Checked my network tab. The connection to firebaseio.com was taking way too long:
![screen shot 2016-04-12 at 21 59 38](https://cloud.githubusercontent.com/assets/92843/14473825/3b5e45f2-00fa-11e6-8639-e191b8eec189.png)

I checked firebase status against our endpoint `s-usc1c-nss-125` – http://status.firebase.com/1962720 and no outages have been reported so far, which is why it’s weird. Let’s revisit tomorrow

**Comment by karolsojko** [comment]
Closing since we don't user Firebase anymore

production soon to be released
