### ISSUE TITLE
Fix unread comments counter for removed cards

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#19]
Low priority. In case a card with unread comments gets removed, make sure that IDs of unread comments in that card are removed from an array of unread comments in the card owner’s account.

**Comment by kbdbrnwsk** [comment]
@theanxy, has this been fixed yet...? :)

**Comment by jkbdbrnwsk** [comment]
@theanxy ping ping :)

**Comment by theanxy** [comment]
Not yet. I’ll take a look

**Comment by Tade0** [comment]
Hi guys, I'm back. Mind if I take this one?

**Comment by theanxy** [comment]
@Tade0 sure thing!

**Comment by jkbdbrnwsk** [comment]
Aaand on this, @Tade0 :) Cheers!

**Comment by Tade0** [comment]
I got something stashed, but I need to confirm that it works. :) Delivering this either 7.04 or 8.04.

**Comment by Tade0** [comment]
Note to self: don't give deadlines when you're not sure about the scope of the problem. :)

**Comment by Tade0** [comment]
Status update:
-newComments was indeed put as a child of root (as suspected in #106), so I fixed that - thanks to that the unread comments badge now works.

Remaining issues:
-I wanted to simply mark comments as read before a card is removed, but that doesn't seem to work.
-There's a mysterious "unread" child of the user record in the DB. It's not used by the unread comments badge, because the number on the badge is calculated, not fetched from the DB.
-There are some classes not connected with any style(or so it appears).

I pushed my progress here:
https://github.com/x-team/unleash/tree/fix-unread-comments-%2319
so you guys can have a look.

**Comment by theanxy** [comment]
Fair enough. See if you can fix it, and if you're stuck, let me know :)

**Comment by Tade0** [comment]
That `incrementCommentCount` was actually ok - it's the method that's invoking it that required change. Continuing.

**Comment by Tade0** [comment]
I read through the `mockfirebase` tutorials and I think there's a way to test this(and other features requiring multi-user database interactions) without resorting to creating e2e tests that touch the DB.

I'll create a PR as soon as I have something that works.
