### ISSUE TITLE
Refactor Redux Actions and Reducers

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#245]
## ACTION

Before:

```
...

export const SKILL_LIST = 'SKILL_LIST';
export const SKILL_LIST_SUCCESS = 'SKILL_LIST_SUCCESS';
export const SKILL_LIST_FAILURE = 'SKILL_LIST_FAILURE';

function doSkillList() {
  return { type: SKILL_LIST };
}

export function skillListSuccess(skills) {
  return { type: SKILL_LIST_SUCCESS, skills };
}

export function skillListFailure(errors) {
  return { type: SKILL_LIST_FAILURE, errors };
}

export function skillList() {
  return (dispatch) => {
    dispatch(doSkillList());

    return fetch(config.skills_api_url)
      .then(response => response.json())
      .then(skills => dispatch(skillListSuccess(skills)))
      .catch(errors => dispatch(skillListFailure(errors)));
  };
}
```

After:

```
...

export const SKILLS = {
  FETCH: {
    START: 'FETCH_SKILLS_START',
    SUCCESS: 'FETCH_SKILLS_SUCCESS',
    FAILURE: 'FETCH_SKILLS_FAILURE',
  }
};

export function fetchSkills() {
  return (dispatch) => {
    dispatch({ type: SKILLS.FETCH.START });

    return fetch(config.skills_api_url)
      .then(response => response.json())
      .then(skills => dispatch({ type: SKILLS.FETCH.SUCCESS, skills }))
      .catch(errors => dispatch({ type: SKILLS.FETCH.FAILURE, errors }));
  };
}
```
## REDUCERS

Before:

```
import { SKILLS } from '../actions/SkillActions';

const initialState = {

};

function skillsReducer(skills = {}, action) {
  Object.freeze(skills);

  let newSkills;
  switch (action.type) {
    case SKILL_LIST_SUCCESS:
      newSkills = {};
      action.skills.forEach((skill) => {
        newSkills[skill.name] = skill;
      });
      return newSkills;
    case SKILL_LIST_FAILURE:
      return {};
    default:
      return skills;
  }
}

export default skillsReducer;
```

After:

```
import { SKILLS } from '../actions/SkillActions';

const initialState = {
  list: [],
  isLoading: false
};

function skillsReducer(state = initialState, action) {
  switch (action.type) {
    case SKILLS.FETCH.START:
      return {
        ...state,
        isLoading: true
      };
    case SKILLS.FETCH.SUCCESS:
      return {
        ...state,
        list: action.skills,
        isLoading: false
      };
    case SKILLS.FETCH.FAILURE:
      return {
        ...state,
        isLoading: false
      };
    default:
      return state;
  }
}

export default skillsReducer;
```

Please note that I would suggest to keep skills in an array, not in an object as we do now.

CC @diegodurli - is this what you had in mind too?

**Comment by diegodurli** [comment]
Hi @szymonmichalak and @karolsojko!

This was part of what I had in mind, indeed. For sure it was needed to make more 'immutable', in terms of not having a local variable to hold a state, manipulate it and return.

Great work @szymonmichalak, loved it!

Another part of what I had in mind was to use `https://github.com/pauldijou/redux-act` in order to avoid boilerplate when creating `actions` and `reducers`. Its a great (yet simple) library to just do that.

Taking a priority perspective, for sure your work is the more important. This part I suggested would just be a enhancement in terms of productivity.

**Comment by karolsojko** [comment]
hmm that library looks cool - though I think it might add some level of complexity for new-comers to understand what's going on - I think we could keep it simple for now - what do you think @szymonmichalak ?

**Comment by BartKrol** [comment]
Out of the curiosity - is redux-act that worth it? It removes only some boilerplate (with moving from string constants being the biggest thing), but it also adds some abstraction. Just to be clear - it looks cool, but I would like to learn more why this approach might be better :).

**Comment by diegodurli** [comment]
@BartKrol, imo I think it worth it. It's all about allowing you to not put time in something that don't worth it, like creating repetitive actions (`functions`) returning only a simple object with a `TYPE` in it.
I believe it's a balance: it's not too much abstraction, making it useful without hurting too much (to learn and maintenance).

If you take a look at the majority of actions / reducers we create nowadays, they're really simple (hopefully), and that's where `redux-act` makes you more productive.

We for sure don't need to use guys, no need to make people uncomfortable with it :)

**Comment by kdemoya** [comment]
Although it looks great and makes sense, I'd agree in passing `redux-act` for now just so we don't add a new layer for new contributors and focus on refactoring the Actions/Reducers as well as adding Immutable.

I know @williamcabrera4 was already planning the latter, so he may want to chime in too.

**Comment by BartKrol** [comment]
Right :). I think I agree (definitely about the `functions`). Is it possible to mix it and use alongside standard approach (I guess it is :P). I'd really like to see how it looks like and I guess in an open source project we can do some experimentations :P.

**Comment by diegodurli** [comment]
Definitely it worth taking a look @BartKrol!
Agree a 100% that it's an abstraction and therefore may not suit every project. I see value in adding it once you look at your `actions` file and you see a LOT of simple functions - it becomes a great place to do a refactoring there :)

Let me know what you think once you try it out @BartKrol! :)

**Comment by BartKrol** [comment]
Sure, I'll do! 

Still, is it possible to use it alongside standard string-based approach? Because I wouldn't mind seeing some actions and reducers written with redux-act by you (and I guess @szymonmichalak @kdemoya too) and we can make a decision if we want to move into that route or not :). (It's all about learning I think :))

**Comment by diegodurli** [comment]
Great @BartKrol!

Going to do the following: will be working on this issue here, and I will refactor using the standard approach, but also will prepare the same version using `redux-act` only to show you guys here. We don't need to commit this, only to show you how it would be.

You can use it alongside standard string-based approach for `TYPE` too. Actually, once you send a String to `createAction` function, it will create an `immutable` constant with that string. This will be used to route to a given `reducer`.

**Comment by kdemoya** [comment]
I agree, let's turn this discussion into a PR and see it in action! 💃  @BartKrol @diegodurli

**Comment by diegodurli** [comment]
Awesome guys, here we go! 👍
