### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#271]
The main page (home) should be the Unleash timeline consisting of a list of:
- announcements of someone achieving a goal
- custom prepared news

Prepare a implementation with mocked data for this.
## Synopsis

> "Since we added the Slack integration to the Unleash app - and all updates are being posted automagically, the Unleash Timeline has been somewhat forgotten (unleash-timeline.x-team.com). I'd like to make the Timeline a part of Unleash 2.0 and use it to not only present all the self explanatory goals developers achieve (and thus have them presented there in addition to the Slack channel), but also share all "bigger" news that would require a bit more context than just one sentence to give a full picture."

**Comment by rmariuzzo** [comment]
@karolsojko  What could be behind all “bigger” new?

**Comment by rmariuzzo** [comment]
@x-team/unleash that's the idea I have in my mind. The blank space on the right could be used for something else in the future...

![artboard](https://cloud.githubusercontent.com/assets/439839/19167102/3c3a8238-8bd8-11e6-8765-64fbcc2d8cff.png)

**Comment by kdemoya** [comment]
X-Outpost: Dominican Republic <3

---

I really like the structure in https://unleash-timeline.x-team.com/, I think it would be awesome to try to combine the material cards of your example with a dual-column layout, like the current timeline.

**Comment by williamcabrera4** [comment]
Nice design @rmariuzzo !!!!
Like @kdemoya , love the idea of the X-Outpost in DR.

**Comment by rmariuzzo** [comment]
😛

**Comment by rmariuzzo** [comment]
BTW, that's just a Sketch there's nothing yet implemented until feedback/review based on this initial idea.

**Comment by rmariuzzo** [comment]
Hey @x-team/unleash !

I have added some coding progress on the dashboard.

![screen shot 2016-10-18 at 16 55 35](https://cloud.githubusercontent.com/assets/439839/19496034/b6beb9dc-9553-11e6-940c-fb20ac4f27e4.png)

I'm considering to create a lib to handle the dual vertical timeline, because of some issues I have encountered:

## No collision detection on avatar
<img width="383" alt="x-team unleash 2016-10-18 16-57-52" src="https://cloud.githubusercontent.com/assets/439839/19496122/205d0498-9554-11e6-8466-62a2bb04c6e2.png">

## No intelligent layout (à la Masonry)
<img width="578" alt="x-team unleash 2016-10-18 16-59-56" src="https://cloud.githubusercontent.com/assets/439839/19496176/5e888c1a-9554-11e6-8147-9e3e8e1f1ebd.png">

I have checked the following libraries with no luck:

 - Masonry
 - Isotype
 - Packery
 - Shuffle.js
 - Salvattore

From now on, I will create a small react lib that allow to:

 1. Provide a `<Timeline/>` and `<Event/>` component.
 2. Position each `<Event/>` inside a `<Timeline/>` taking in account its content + pin (i.e.: avatar).
 3. Reposition the pin intelligently to avoid collision with other pins.

Any suggestions?

**Comment by karolsojko** [comment]
@rmariuzzo this stuff is great ! I loved the first proposal as well. 

Though I wouldn't focus _that_ much on final design yet. Once we have the functionalities in place we will have someone design the whole app and implement the design so it's consistent across the whole application. 

So as for the fact if they are in a unleash timeline or not I wouldn't go that deep for choosing libraries - let's just have the business logic behind and display it in a simplest manner :)

Nevertheless great work Rubens 💪

**Comment by rmariuzzo** [comment]
Hey @karolsojko!

I'm back! Here is a preview of the current state of the proposal. The vertical chronology is implemented properly.

![screen shot 2016-11-08 at 18 16 51](https://cloud.githubusercontent.com/assets/439839/20119599/8b8b7330-a5df-11e6-8e7f-cf082fff30b6.png)

**Comment by rmariuzzo** [comment]
Rebased with latest `develop`.

**Comment by jkbdbrnwsk** [comment]
Love it, @rmariuzzo! Especially that I wanted to revive the Unleash Timeline in order to write about bigger stories, not necessarily being covered just by the bot notifications. Cheers!

**Comment by karolsojko** [comment]
@rmariuzzo can you put out a PR with this ?
