### ISSUE TITLE
Group and pack components into modules

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#376]
### WIP: Please do not assign and do not work on this task!

Instead of having components in the [current form](https://github.com/x-team/unleash/tree/develop/app/components), I would suggest to group them:

- goals
- skills
- paths
- ...
- common

Also, each component should have it's own directory:

```
app/components/goals/AddExistingModal
|__AddExistingModal.jsx
|__AddExistingModal.spec.js
|__styles.js
|__index.js
```

As you can see, I would also want to suggest to move `styles` out of component, move it to a separate file.

Please react 👍 / 👎 and write some comments!

**Comment by szymonmichalak** [comment]
@kdemoya could you please elaborate a little bit?

**Comment by kdemoya** [comment]
Yes @szymonmichalak, I believe our current (flatter) structure is working fine. Trying to over organize them will add a lot of boilerplate we don't currently have to deal with.

I may agree on grouping components on folders like `goals`, `skills`, `paths`. But I don't agree on adding one folder plus two more files per each component, that'd take us to ~22 new folders and ~44 new files (with the current count).

Meaning we would go from:

1. Create your component file.
2. Create your test file.

to:

1. Create a new folder for your component.
2. Create your component file.
3. Create your test file.
4. Create your styles file.
5. Create an index file to export your component.

And that's without counting the containers and reducers.

**Comment by szymonmichalak** [comment]
Please take a look at this example: https://github.com/x-team/unleash/blob/develop/app/components/GoalCard.jsx

Almost 300 lines, mixing JS and styles... it's awful, sorry!

The **main purpose** of that issue is to extract those styles from components and get rid of declaring 

```let styles = {}``` 

at the beginning of each file. You forgot about that in your "2-step" process, @kdemoya.

In order to extract those styles, I suggested to pack them into modules...

**Comment by kdemoya** [comment]
I did not forget about that and I understood what your suggestion was, @szymonmichalak, but +22 folders and +44 new files would seem as (if not more) awful to me.

But hey, that's just my opinion. :)

**Comment by szymonmichalak** [comment]
So you just weren't fair if you didn't forget! 😄 

If it just about numbers, you know that we can reduce that number. Component could be called `index.js` in the specific folder, but I am not convinced to that.

After couple of big projects in React I figured out that this structure is the best (at least for me) - nice, clear and predictable. Easy to find everything you want, everything packed into modules, easy! 

I'm just not convinced that the number of files that you have to create is a problem here. When it's done, how long would it take to create a new component? Extra few seconds? An extra minute maybe?

Thanks a lot @kdemoya for that valuable discussion. Now let others vote and comment on that :-)

**Comment by kdemoya** [comment]
I don't believe we have use a sarcastic tone to make a point, @szymonmichalak. I'm talking about the number of folders and files created here, not about what goes inside them. And my opinions are also based on a couple of big React projects, for that matter.

I do understand your position, I'm just explaining mine. Let's relax a bit here, shall we? 😉

**Comment by szymonmichalak** [comment]
Not sure where I was sarcastic throughout our discussion 🤔 Sorry if you felt so, but I assure you it wasn't my intention. I'm just trying to give more context, reasoning to you and all the others that will read that thread and try to decide what's best. **No pressure at all** and I felt our comments were just "loud thoughts", relaxed too.

I also do understand your position and if the majority is in favour of the approach you follow, then let's keep it the way it is. 🤝 @kdemoya !

**Comment by bernardodiasc** [comment]
Hey folks, not active contributor here, but contributing with some thoughts. This is personal opinion with some reasoning behind, it's not my final thoughts on the subject, but something I have been using lately. On my projects I use this pattern:

```
ComponentName/
│   └── components
│       ├── SubComponentName1
│       |   └── ...
│       └── SubComponentName2
│           └── ...
├── README.md
├── index.js
├── ComponentName.css
├── ComponentName.js
└── ComponentName.spec.js
```

It have plenty boilerplate, yes, indeed. This is not a bad thing, on workflow it causes no trouble. In a big project, costs are outweighed by the benefits. In general, benefits are organisation and predictability.

## Reasons:

1. **Component folder:** organise component stuff inside the component folder kinda pack the thing and isolate from the other non-related things;
2. **Sub-components folder:** the `components` folder allows organise dependent components inside the responsible component;
3. **Readme doc:** this markdown have some information about what component is, how it works, how to use, data structures, and other many useful information. Sometimes the component is super simple, and have the online example of it's usage is still good to have. This file is the one that appears on the component folder page on github. Among other benefits...;
4. **The index file:** this is tricky. why have? why don't? "index" is old terminology on our field, it's the root file of given path, the one that the programs will look first in the folder. So, it's not the place for the component, but important to have in the folder, so:
    - one can  import the component using `import ComponentName from './ComponentName';`
    - if the application require enhancements in the components, the HOCs can be declared in the `index.js` (that most of the times all this file will contain is: `export default from './ComponentName';`);
    - this way tests still can be performed in the pure components if you call the `ComponentName.js` directly in test file;
5. **ComponentName css file:** the styles goes in a CSS (if uses css, js if uses js) because styles can consume many LoC and it's strange to have this kind of code together. This is very personal opinion. Ah, why `ComponentName.css` instead `styles.css`? because when you open `styles.css` it means not much, it means "styles of something", this name require the context of the folder to make sense, while `ComponentName.css` is clearly the styles of the component, when editing styles of several components, the tab names in the editor will not be problem;
6. **The ComponentName js file:** here lives the React component, most of times as stateless (pure function), but stateful are totally fine;
7. **Tests:** for tests I use `ComponentName.spec.js`, I don't have any preference against others about tests organisation;

## Containers and Displays

The so called "smart and dumb" components, I like to call "container and display". In my projects I have components that handle only display, it's where all HTML and CSS lives. They are 100% reusable and decoupled of the application. The file system structured of display components looks like the above.

To put simple, container components handles the business logic, don't have any HTML and CSS, it will do all the logic until it gets to render display components. For containers, some things more in the file system:

```
ComponentNameContainer/
│   └── components
│       ├── SubComponentName1Container
│       |   └── ...
│       └── SubComponentName2
│           └── ...
├── README.md
├── index.js
├── actions.js
├── reducer.js
├── selectors.js
├── ComponentNameContainer.css
├── ComponentNameContainer.js
└── ComponentNameContainer.spec.js
```

Explaining, pretty much the same of a display component with some additions:

1. **Naming:** container components receive the "Container" appendix. Also, I have no problem at all with big names, they are self-explanatory, this even help decreasing the amount of documentation needed;
2. **Sub-containers:** it's ok to have sub containers, it makes sense and reduces the dependency of components have on each other. This is Redux 101 I think: have a clear vision of Redux state object and use containers to connect to the store and wrap displays whenever needed (e.g. a table can be contained, as could be the table cells);
3. **Redux:** in the app I use this pattern we use Redux, so we have `actions.js` for constants and action creators and `reducer.js` for reducers. Ideally most calculations goes on actions, reducers then take care of merging data. Not much reasoning on file names here;
4. **Selectors:** I learned this recently and enjoying this approach, that consists in abstract the unit functions that gets data from state as selectors. I use selectors for helper functions too, and get values from data structures other than Redux state, etc.
    - handy usage of selectors is for unit test approach, import the selectors in the test file, write the specs and unit test it, this is great for documentation as well (the specs!)
    - handy for reduce amount of logic inside the component, one can use a select function to map state to props, such as:

```js
// ComponentNameContainer/selectors.js
import R from 'ramda';

export const getSomethingFromState = (state = {}) => (
  R.view(R.lensPath(['some', 'thing']), state) || ''
);
```

```js
// ComponentNameContainer.js
...

const mapStateToProps = (state) => ({
  something: getSomethingFromState(state),
});

export default connect(mapStateToProps, mapDispatchToProps)(ComponentName);
```

---

Alright, there is a lot reasoning there, not everything is best approach in fact or final solution, a lot things are pure personal opinion, and goes on. I hope it helps to enrich the discussion on this topic. 😄 

Cheers! 👋

**Comment by nicksp** [comment]
To sort of support the previous comment and give you guys some "semi-real" example of outlined ideas, i'd like to share with you the project of mine i'm working on occasionally https://github.com/nicksp/redux-webpack-es6-boilerplate

It's suitable for scalable applications and organised using the custom variation of the [Ducks pattern](https://github.com/erikras/ducks-modular-redux) — approach when each module's entry file (feature-name.js) contains all of its related constants, actions/action creators, selectors and its reducer.

Hope that helps you in one way or another :-)

**Comment by karolsojko** [comment]
I'm a bit hesitant about this - but in general the current structure is pretty ok since we don't have a biiig project. Also there is a potential risk of everything landing in the `common` section. 

Don't have a really strong opinion about this, but would in general keep as is until the projects grows significantly

**Comment by szymonmichalak** [comment]
@bernardodiasc, @nicksp could you please help me decide on this? Don't want to force my way of doing it if there are some votes against. I'm asking you directly, since your point of view is quite similar to mine.

**Should we just leave it the way it is (for now, until project gets bigger) or do you suggest to proceed anyway?**

**Comment by bernardodiasc** [comment]
IMHO, while premature optimising is not a good call, optimising in a good timing is very good call. I didn't get chance to work on this code base yet, but what I think is: if not now, when? how? why?

What I mean is, this don't need to be made now as it's pointed as unneeded but what is the planning for future optimisations?

I usually like to have docs explaining the current patterns, patterns that fits for the current state/size/complexity of the application, and then I create tasks to upgrade patterns, and when the need comes, it's all planned and documented already.

**Comment by karolsojko** [comment]
It's not that kind of an application :) It's purpose is to both serve all Unleashing purposes but also be a pleasure to contribute to for all X-Teamers interested. No need to kill it with stacks of documentation and architectural planning - I think we can contain everything within discussion on github. 

When it comes to optimization I think it is premature now and don't see the need to establish or plan when it will be a good time for it. I think we'll React (pun intended) when we feel it's right :)

**Comment by bernardodiasc** [comment]
You making look like docs and planning are something brutal for monster apps haha A doc can be 1 markdown file, a plan can be one GH issue. ;)
