### ISSUE TITLE
Move constants to a config / constants file

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#378]
### WIP: Please do not assign and do not work on this task!

An example: `googleDefaultImage` in [UserCard.jsx](https://github.com/x-team/unleash/blob/develop/app/components/UserCard.jsx#L15) component.

I would suggest to move all such constants to a global config / constants file.

Please react 👍 / 👎 and write some comments!

**Comment by dash-** [comment]
Hard-coded values should not be in the source.  Good catch there! 👍 

Regarding config/constants file, I am super new, and basically an outsider still.  I haven't even seen the source for this project yet.  However, my preferred method of configuring React apps, as recommended by 12 Factor App (1), and what I've seen to be the most common config approach for pro node.js / react applications, is to use environment variables rather than proper config files.

Create-react-app even automates the process of copying specified remote env variables to the client side, and is configurable after the app is ejected.

(1) https://12factor.net/config

**Comment by nicksp** [comment]
@dash- Thanks for your valuable tips across different issues. I learn from it. 

Speaking about the `env` file usage, yes that's sort of what the project's [already utilising](https://github.com/x-team/unleash/blob/develop/config.js) but it should be extended in terms of contained data inside it. At the moment it's just different resource/API endpoint configs, but could easily contain anything else which is meant to be a proper constant :)

**Comment by dash-** [comment]
I agree 100%.  There's no reason resource/API endpoints should be the extent of configuration -- and you've certainly identified a variable that should be part of that config.

I wouldn't consider the config.js file you linked to as being an approach that follows 12-Factor App's recommendation -- that's just a JS file containing configuration, which is probably less common than JSON config files (but has the advantage of allowing comments).  But neither JS nor JSON files are environmental variable configuration approaches, which are typically shell/bat scripts, and are not typically checked into a repository.

Of course, there are pros and cons to any configuration approach, and I think it's tangential to your point (which is 100% correct).  If there's already a configuration approach in place (which there obviously is), it would make sense to at least use that approach to capture the configuration rather than having configuration data hard-coded into the application itself.

**Comment by karolsojko** [comment]
I think we all agree to put those in a const/config file - think this one could be closed and referenced in a potential PR - @szymonmichalak do you agree ?
