### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#40]

**Comment by singerxt** [comment]
@kbdbrnwsk We can expect any designs ? If not I can start working on that without designs just a lot of feedback will be needed ;-)

**Comment by theanxy** [comment]
It would be good to at least have rough mobile wireframes to have something to follow, especially if we’re going to work it together with @singerxt. Otherwise we will need to split responsibilities and work on making specific parts responsive by ourselves.

I suppose for grid interfaces like the list of users and cards, we will just decrease the amount of items in row – simple enough. Most likely we won’t need to make the admin–only edit profile and edit templates pages responsive.

However, we need a direction on how to:
- style menu on mobile,
- handle viewing cards. 

For the menu, we could simply use a html5 select element.

For viewing cards, I suggested creating a separate angular view with card details and its comments. This would be instead of the sidebar. We would need to add a different onclick action depending on the breakpoint. The URL structure would remain the same (on desktop: show user index page and animate the sidebar, on mobile: show a card detail page).

What do you think?

**Comment by karolsojko** [comment]
I think we can close this one since it's obsolete - @jkbdbrnwsk @theanxy ?

**Comment by jkbdbrnwsk** [comment]
We are probably going to implement "responsiveness" with the new graphic layout, so let's close it for now.
