### ISSUE TITLE
Automatic database backup

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#55]
Database should be automatically backed up every 12h (only in case some changes were made).

**Comment by karolsojko** [comment]
Regarding this - I thought maybe we could migrate to MongoDB

Firebase is quite limiting I think - @theanxy what's your thoughts ?

**Comment by Tade0** [comment]
_Imma fet you finish, but Firebase had one of the best databases of all time_ `</kanyewest>`

@karolsojko Are you sure about this move? To me it looks like this would require a rewrite of the app.

**Comment by karolsojko** [comment]
It's not a move - just starting a conversation ;) 

Yeah, it would require some refactoring but in general we would have more control of the db + could spin up an instance on local environment with Docker, automatic backups would be easier. Automatic backups are a paid feature in Firebase.

**Comment by theanxy** [comment]
Rewriting the app only to switch the DB doesn't sound too feasible, since large amount of code is vendor-specific. Firebase remains free for our use cases, too.

Using Firebase made sense especially at the beginning since we used to host the app on Firebase server as well. I’d probably chose Mongo if we were to start self-hosted right away, but I don't think it would bring us any additional value right now. So I think we made a good choice after all and I'm still a big fan of Firebase.

Thankfully there's plenty of 3rd party tools to backup firebase automatically, e.g. https://github.com/designed27/firebase-backup-s3-python or https://github.com/CurtisHumphrey/node-firebase-backup. I was going to start working on it later today anyway – so I'll let you know when it's ready :relaxed:

**Comment by theanxy** [comment]
If you can think of anything else that could limit the project because of Firebase, please let me know.

**Comment by karolsojko** [comment]
Nope. The python/node scripts sound very good - good points :+1:

**Comment by karolsojko** [comment]
Talked to Josh about this and waiting for him to provide us with an AWS account so we can upload the backups to S3 daily.

**Comment by karolsojko** [comment]
Fixed with https://github.com/karolsojko/firebase-s3-backup

the database is backed up daily on our X-Team S3 Bucket :)
