### ISSUE TITLE
Disposable cards

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#74]
Currently, in order to add a card to a Path, a template needs to be created and dragged to the appropiate dropbox. After months of using the application, turns out that most of the templates were used only once, and this trend seems to persist. This has led to having a super long list of templates that are not being used anymore. They can be deleted, but that disqualifes the idea of “templates”.

Please add a feature that will enable Path-builders to create cards right in the “Edit path” panel - cards that will be used only once and tied with a particular Path.

![screenshot 2015-06-23 14 28 17](https://cloud.githubusercontent.com/assets/7212882/8305995/6c40ad3c-19b4-11e5-862e-71910d789179.png)

**Comment by ryanchartrand** [comment]
Love this! /five

On Tue, Jun 23, 2015 at 5:31 AM, kbdbrnwsk <notifications@github.com> wrote:

> Currently, in order to add a card to a Path, a template needs to be
> created and dragged to the appropiate dropbox. After months of using the
> application, turns out that most of the templates were used only once, and
> this trend seems to persist. This has led to having a super long list of
> templates that are not being used anymore. They can be deleted, but that
> disqualifes the idea of “templates”.
>
> Please add a feature that will enable Path-builders to create cards right
> in the “Edit path” panel - cards that will be used only once and tied with
> a particular Path.
>
> [image: screenshot 2015-06-23 14 28 17]
> <https://cloud.githubusercontent.com/assets/7212882/8305995/6c40ad3c-19b4-11e5-862e-71910d789179.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x-team/unleash/issues/74>.
>



-- 


Ryan Chartrand
CEO | X-Team LLC | Los Angeles
ryan@x-team.com | 310-866-8382
www.x-team.com

**Comment by kbdbrnwsk** [comment]
Thanks, @Tade0! It works great!

I have one concern regarding the left column, though. Seems it's not sticky, after all: http://screencast.com/t/hwvUVe0o9FrK

**Comment by kbdbrnwsk** [comment]
Anyway, I'd like to start using "Create quick card" button ASAP (have some Paths to update), so will appreciate deploying this feature to production, @theanxy! Cheers!

**Comment by Tade0** [comment]
@kbdbrnwsk if this is happening on staging(where you in particular have a lot of cards) then it's probably because the column with the cards is longer than the column with the templates.

But now that you mentioned it I think we'll have an problem when the left column gets long enough not to fit in the screen but still remains shorter than the right column.

I'll think of something for this.

**Comment by kbdbrnwsk** [comment]
Thanks, @Tade0! Appreciate!

I played with it a little bit more on production this time... and the bug is interesting. :) Take a look: http://screencast.com/t/rEZlngsq

If you scroll down far enough, the dropbox suddenly appears. :)

**Comment by kbdbrnwsk** [comment]
Hmmm... I've noticed something else, strange we didn't think about it before. :D If the dropbox is longer than the height of you screen... this happens: https://www.dropbox.com/s/n4lf2oh5yvjy7mn/Screenshot%202015-07-23%2022.02.00.png?dl=0

Basically you can't drag'n'drop the template to the bottom of the dropbox... because it's hidden below the screen's edge.

If such situation occurs (path is higher than admin's screen), would it be possible to stick the dropbox to the bottom edge of the screen, or center it vertically?

**Comment by Tade0** [comment]
Ouch - this looks bad. What browser are you using?

As for sticking the dropbox to the bottom - no problem. Centering it vertically could prove tricky.

**Comment by kbdbrnwsk** [comment]
Google Chrome.

We'll just need to make enough room for the remove cards box + "Create a quick card" button, so they are displayed as well. So basically the whole block needs to be sticked.
